import type { BusinessInfo, Review, BusinessAnalysis, Workflow } from './discover-types'

const REVIEWS: Review[] = [
  { author: 'Sarah M.', rating: 2, text: "The coffee is amazing but I waited 25 minutes for a simple latte. This happens every time during morning rush.", date: '2 days ago', sentiment: 'negative' },
  { author: 'James K.', rating: 1, text: "Came in for a quick coffee before work. 30 minute wait. Staff seemed overwhelmed and a bit rude when I asked.", date: '4 days ago', sentiment: 'negative' },
  { author: 'Alex P.', rating: 5, text: "Best oat milk latte in the Mission! Worth the wait. The baristas clearly care about quality.", date: '5 days ago', sentiment: 'positive' },
  { author: 'Michelle T.', rating: 3, text: "Good coffee but never enough outlets for laptops. I come here to work and always fight for a plug.", date: '1 week ago', sentiment: 'negative' },
  { author: 'David R.', rating: 4, text: "Love the vibe, great pastries. Wish they had mobile ordering to skip the line.", date: '1 week ago', sentiment: 'positive' },
  { author: 'Nina L.', rating: 2, text: "Asked about WiFi password 3 times and got different answers. Google says free WiFi but it barely works.", date: '1 week ago', sentiment: 'negative' },
  { author: 'Carlos G.', rating: 5, text: "The seasonal specials are incredible. The lavender honey latte changed my life.", date: '2 weeks ago', sentiment: 'positive' },
  { author: 'Rachel W.', rating: 1, text: "Left a negative review a month ago and no one responded. Shows how much they care.", date: '2 weeks ago', sentiment: 'negative' },
  { author: 'Tom H.', rating: 4, text: "Consistently great coffee. Only complaint is parking — none nearby.", date: '2 weeks ago', sentiment: 'positive' },
  { author: 'Jessica B.', rating: 2, text: "Menu on Google is completely wrong. Showed up expecting breakfast burritos — haven't had those in months.", date: '3 weeks ago', sentiment: 'negative' },
  { author: 'Mark D.', rating: 3, text: "WiFi keeps cutting out. I like working here but can't rely on the internet.", date: '3 weeks ago', sentiment: 'negative' },
  { author: 'Lauren S.', rating: 5, text: "The baristas actually remember my order! Love that personal touch.", date: '3 weeks ago', sentiment: 'positive' },
  { author: 'Kevin O.', rating: 2, text: "Tried calling ahead about catering and no one picked up. Called 4 times.", date: '3 weeks ago', sentiment: 'negative' },
  { author: 'Amy C.', rating: 4, text: "Great ambiance for dates. A bit noisy during peak hours but otherwise perfect.", date: '1 month ago', sentiment: 'positive' },
  { author: 'Brian F.', rating: 1, text: "They messed up my order twice. When I pointed it out, the barista seemed annoyed. No apology.", date: '1 month ago', sentiment: 'negative' },
  { author: 'Priya N.', rating: 5, text: "The pour-over is world class. They source from incredible farms. Worth every penny.", date: '1 month ago', sentiment: 'positive' },
  { author: 'Jason L.', rating: 3, text: "Is there parking? Can't find info anywhere. Had to circle the block 3 times.", date: '1 month ago', sentiment: 'negative' },
  { author: 'Emma R.', rating: 2, text: "Instagram says they close at 8pm but I showed up at 7:30 and they were closed.", date: '1 month ago', sentiment: 'negative' },
  { author: 'Chris Z.', rating: 4, text: "The cold brew is phenomenal. Wish the website had a menu with prices.", date: '1 month ago', sentiment: 'positive' },
  { author: 'Sophia V.', rating: 1, text: "Found a hair in my drink. Staff just offered to remake it with no real apology.", date: '5 weeks ago', sentiment: 'negative' },
  { author: 'Daniel M.', rating: 5, text: "Incredible latte art. These baristas are artists.", date: '5 weeks ago', sentiment: 'positive' },
  { author: 'Katie P.', rating: 2, text: "20 minute wait for drip coffee? There should be a fast lane for simple orders.", date: '6 weeks ago', sentiment: 'negative' },
  { author: 'Ryan H.', rating: 4, text: "Fresh croissants, always good coffee. A bit pricey but you get what you pay for.", date: '6 weeks ago', sentiment: 'positive' },
  { author: 'Lisa T.', rating: 3, text: "Been coming for a year and still no mobile ordering. Every other café has it.", date: '6 weeks ago', sentiment: 'negative' },
  { author: 'Olivia J.', rating: 2, text: "They never respond to reviews — not even bad ones. Don't care about improving.", date: '2 months ago', sentiment: 'negative' },
  { author: 'Zoe A.', rating: 1, text: "Online menu hasn't been updated in forever. Half the items aren't available.", date: '2 months ago', sentiment: 'negative' },
  { author: 'Tyler B.', rating: 5, text: "My go-to spot. Staff is incredible, coffee is perfect, playlist always on point.", date: '2 months ago', sentiment: 'positive' },
  { author: 'Hannah G.', rating: 3, text: "Do they do events? Asked about a birthday booking and nobody knew.", date: '3 months ago', sentiment: 'neutral' },
]

export const MOCK_BUSINESS: BusinessInfo = {
  id: 'mock-coffee-1',
  name: "Brew & Bean Café",
  type: 'Coffee Shop',
  rating: 4.2,
  review_count: 847,
  address: '1247 Valencia St, San Francisco, CA 94110',
  phone: '(415) 555-0182',
  website: 'https://brewandbean.cafe',
  hours: 'Mon-Fri 6AM-8PM, Sat-Sun 7AM-9PM',
  price_level: '$$',
  maps_url: 'https://maps.google.com/maps?q=brew+and+bean+cafe',
  scraped_at: new Date().toISOString(),
  reviews: REVIEWS,
}

const MOCK_WORKFLOWS: Workflow[] = [
  {
    id: 'wf-review-responder',
    name: 'Smart Review Responder',
    description: 'Monitors Google reviews and drafts personalized responses. Analyzes sentiment and generates empathetic replies addressing specific complaints.',
    trigger: 'Every 4 hours',
    tools_used: ['browser', 'llm', 'tts'],
    user_facing: true,
    actions: [
      'Browse Google Maps listing for new reviews',
      'Analyze review sentiment and extract key complaints',
      'Generate personalized response acknowledging issues',
      'Draft response for owner approval or auto-post',
      'Alert owner via voice summary for severe complaints',
    ],
    eval_metrics: [
      { name: 'response_posted', description: 'Was a response posted?', type: 'boolean' },
      { name: 'response_time_hrs', description: 'Hours between review and response', type: 'number', target: 4 },
      { name: 'sentiment_match', description: 'Response tone matches severity', type: 'percentage', target: 90 },
      { name: 'review_updated', description: 'Customer improved their review', type: 'boolean' },
    ],
    pain_point_id: 'unresponsive_reviews',
    status: 'suggested',
    confidence: 0.94,
  },
  {
    id: 'wf-phone-agent',
    name: 'AI Phone Receptionist',
    description: 'Voice AI that answers calls, handles common questions (hours, parking, menu), takes catering inquiries, and transfers to staff for complex requests.',
    trigger: 'Inbound phone call',
    tools_used: ['voice', 'tts', 'llm', 'calendar'],
    user_facing: true,
    actions: [
      'Answer inbound call with friendly greeting',
      'Identify caller intent (hours, menu, catering, reservation)',
      'Answer from knowledge base built from website + menu',
      'For catering → collect details + schedule callback',
      'For complaints → empathize, log, alert manager',
    ],
    eval_metrics: [
      { name: 'call_answered', description: 'Was the call picked up?', type: 'boolean' },
      { name: 'intent_accuracy', description: 'Correctly identified caller intent', type: 'percentage', target: 85 },
      { name: 'resolution_rate', description: 'Resolved without transfer', type: 'percentage', target: 70 },
      { name: 'caller_satisfaction', description: 'Post-call rating', type: 'number', target: 4 },
    ],
    pain_point_id: 'phone_unanswered',
    status: 'suggested',
    confidence: 0.91,
  },
  {
    id: 'wf-listing-sync',
    name: 'Listing & Menu Sync Checker',
    description: 'Browses all online listings (Google, Yelp, website, Instagram), compares menus/hours/pricing, and flags discrepancies.',
    trigger: 'Weekly Monday 9 AM',
    tools_used: ['browser', 'image_model', 'llm'],
    user_facing: false,
    actions: [
      'Browse Google Maps listing → extract menu & hours',
      'Browse Yelp → extract menu & hours',
      'Browse business website → extract menu & hours',
      'Use vision AI to read menu images/PDFs',
      'Compare all sources → flag discrepancies',
      'Generate report with specific fixes needed',
    ],
    eval_metrics: [
      { name: 'platforms_checked', description: 'Platforms scanned', type: 'number', target: 4 },
      { name: 'discrepancies_found', description: 'Mismatches detected', type: 'number' },
      { name: 'issues_fixed', description: 'Flagged issues resolved', type: 'boolean' },
      { name: 'accuracy', description: 'Detection accuracy', type: 'percentage', target: 95 },
    ],
    pain_point_id: 'outdated_online_info',
    status: 'suggested',
    confidence: 0.88,
  },
  {
    id: 'wf-queue-monitor',
    name: 'Wait Time & Queue Monitor',
    description: 'Monitors review mentions of wait times, cross-references Google Popular Times, predicts rushes, and alerts staff for proactive staffing.',
    trigger: 'Every 30 min',
    tools_used: ['browser', 'sms', 'llm', 'camera'],
    user_facing: false,
    actions: [
      'Analyze recent reviews for wait time mentions',
      'Cross-reference with Google Popular Times data',
      'Predict upcoming rush based on day/time patterns',
      'Alert staff 30 min before predicted rush via SMS',
      'Suggest adding extra barista during peak windows',
      'Track if wait complaint frequency decreases over time',
    ],
    eval_metrics: [
      { name: 'rush_predicted', description: 'Rush correctly predicted', type: 'boolean' },
      { name: 'alert_sent', description: 'Staff alerted before rush', type: 'boolean' },
      { name: 'complaint_reduction', description: 'Wait complaint reduction', type: 'percentage', target: 30 },
      { name: 'prediction_accuracy', description: 'Accuracy vs actual', type: 'percentage', target: 75 },
    ],
    pain_point_id: 'long_wait_times',
    status: 'suggested',
    confidence: 0.82,
  },
  {
    id: 'wf-qa-responder',
    name: 'Auto Q&A Responder',
    description: 'Monitors Google Q&A section and unanswered questions in reviews. Drafts accurate answers from business knowledge base.',
    trigger: 'Daily 10 AM',
    tools_used: ['browser', 'llm'],
    user_facing: true,
    actions: [
      'Browse Google Maps Q&A for unanswered questions',
      'Scan reviews for questions posed by customers',
      'Match questions to knowledge base (hours, parking, WiFi)',
      'Draft clear, helpful answers',
      'Post or queue for owner approval',
    ],
    eval_metrics: [
      { name: 'questions_answered', description: 'Questions responded to', type: 'number' },
      { name: 'answer_accuracy', description: 'Matches verified info', type: 'percentage', target: 95 },
      { name: 'response_time', description: 'Hours from question to answer', type: 'number', target: 24 },
    ],
    pain_point_id: 'unanswered_questions',
    status: 'suggested',
    confidence: 0.86,
  },
]

export const MOCK_ANALYSIS: BusinessAnalysis = {
  business_id: 'mock-coffee-1',
  business_type: 'coffee_shop',
  pain_points: [
    {
      issue: 'long_wait_times',
      label: 'Long Wait Times',
      frequency: 14,
      severity: 'high',
      example_quotes: [
        "I waited 25 minutes for a simple latte",
        "30 minute wait. Staff seemed overwhelmed",
        "20 minute wait for drip coffee?",
      ],
    },
    {
      issue: 'unresponsive_reviews',
      label: 'No Review Responses',
      frequency: 8,
      severity: 'high',
      example_quotes: [
        "Left a negative review and no one responded",
        "They never respond to reviews — not even bad ones",
      ],
    },
    {
      issue: 'outdated_online_info',
      label: 'Outdated Menu & Hours',
      frequency: 10,
      severity: 'medium',
      example_quotes: [
        "Menu on Google is completely wrong",
        "Online menu hasn't been updated in forever",
        "Instagram says 8pm but they were closed at 7:30",
      ],
    },
    {
      issue: 'phone_unanswered',
      label: 'Phone Unanswered',
      frequency: 4,
      severity: 'medium',
      example_quotes: [
        "Tried calling and no one picked up. Called 4 times.",
      ],
    },
    {
      issue: 'unanswered_questions',
      label: 'Common Questions Unanswered',
      frequency: 6,
      severity: 'low',
      example_quotes: [
        "Is there parking? Can't find info anywhere",
        "Do they do events? Nobody knew",
      ],
    },
  ],
  strengths: [
    { label: 'Coffee Quality', mentions: 18 },
    { label: 'Ambiance & Vibe', mentions: 12 },
    { label: 'Friendly Staff', mentions: 8 },
    { label: 'Pastries & Food', mentions: 6 },
  ],
  unanswered_questions: [
    'Is there parking nearby?',
    'Do you have reliable WiFi?',
    'Can I book for events or parties?',
    'Do you offer catering?',
    'What are the actual current hours?',
  ],
  suggested_workflows: MOCK_WORKFLOWS,
  analyzed_at: new Date().toISOString(),
}
