import type { BusinessInfo, Review, BusinessAnalysis, Workflow } from './discover-types'

export const MOCK_BUSINESS: BusinessInfo = {
  id: 'mock-coffee-1',
  name: "Brew & Bean Café",
  type: 'Coffee Shop',
  rating: 4.2,
  reviewCount: 847,
  address: '1247 Valencia St, San Francisco, CA 94110',
  phone: '(415) 555-0182',
  website: 'https://brewandbean.cafe',
  hours: 'Mon-Fri 6AM-8PM, Sat-Sun 7AM-9PM',
  priceLevel: '$$',
  mapsUrl: 'https://maps.google.com/maps?q=brew+and+bean+cafe',
  scrapedAt: new Date().toISOString(),
}

export const MOCK_REVIEWS: Review[] = [
  { author: 'Sarah M.', rating: 2, text: "The coffee is amazing but I waited 25 minutes for a simple latte. This happens every time during morning rush. They need more baristas.", date: '2 days ago', sentiment: 'negative' },
  { author: 'James K.', rating: 1, text: "Came in for a quick coffee before work. 30 minute wait. The staff seemed overwhelmed and honestly a bit rude when I asked how long. Won't be back.", date: '4 days ago', sentiment: 'negative' },
  { author: 'Alex P.', rating: 5, text: "Best oat milk latte in the Mission! Worth the wait honestly. The baristas clearly care about quality.", date: '5 days ago', sentiment: 'positive' },
  { author: 'Michelle T.', rating: 3, text: "Good coffee but they never have enough outlets for laptops. I come here to work and always end up fighting for a spot near a plug.", date: '1 week ago', sentiment: 'negative' },
  { author: 'David R.', rating: 4, text: "Love the vibe, great pastries. Wish they had a mobile ordering option so I could skip the line.", date: '1 week ago', sentiment: 'positive' },
  { author: 'Nina L.', rating: 2, text: "Asked about WiFi password 3 times and got different answers. Their Google listing says they have free WiFi but it barely works.", date: '1 week ago', sentiment: 'negative' },
  { author: 'Carlos G.', rating: 5, text: "The seasonal specials are always incredible. The lavender honey latte changed my life. Staff is super friendly.", date: '2 weeks ago', sentiment: 'positive' },
  { author: 'Rachel W.', rating: 1, text: "I left a negative review a month ago about the wait times and no one responded. Shows how much they care about customer feedback.", date: '2 weeks ago', sentiment: 'negative' },
  { author: 'Tom H.', rating: 4, text: "Consistently great coffee. My only complaint is parking — there's none nearby and they don't validate.", date: '2 weeks ago', sentiment: 'positive' },
  { author: 'Jessica B.', rating: 2, text: "The menu on Google is completely wrong. Showed up expecting breakfast burritos and they haven't had those in months. Update your listings!", date: '3 weeks ago', sentiment: 'negative' },
  { author: 'Mark D.', rating: 3, text: "WiFi keeps cutting out. I like working here but can't rely on the internet. Ended up using my hotspot.", date: '3 weeks ago', sentiment: 'negative' },
  { author: 'Lauren S.', rating: 5, text: "The baristas actually remember my order! Love that personal touch. Best coffee shop in SF.", date: '3 weeks ago', sentiment: 'positive' },
  { author: 'Kevin O.', rating: 2, text: "Tried calling ahead to ask about large catering orders and no one picked up. Called 4 times. Do they not answer the phone?", date: '3 weeks ago', sentiment: 'negative' },
  { author: 'Amy C.', rating: 4, text: "Great ambiance for dates. A bit noisy during peak hours but otherwise perfect.", date: '1 month ago', sentiment: 'positive' },
  { author: 'Brian F.', rating: 1, text: "They messed up my order twice and when I pointed it out, the barista seemed annoyed. No apology, nothing.", date: '1 month ago', sentiment: 'negative' },
  { author: 'Priya N.', rating: 5, text: "The pour-over here is honestly world class. They source from incredible farms. Worth every penny.", date: '1 month ago', sentiment: 'positive' },
  { author: 'Jason L.', rating: 3, text: "Is there parking? Every time I search I can't find info. Had to circle the block 3 times.", date: '1 month ago', sentiment: 'negative' },
  { author: 'Emma R.', rating: 2, text: "Their Instagram says they close at 8pm but I showed up at 7:30 and they were already closed. Hours are inconsistent.", date: '1 month ago', sentiment: 'negative' },
  { author: 'Chris Z.', rating: 4, text: "The cold brew is phenomenal. I just wish the app or website had a menu so I could check prices before going.", date: '1 month ago', sentiment: 'positive' },
  { author: 'Sophia V.', rating: 1, text: "Found a hair in my drink. When I told the staff, they just offered to remake it with no real apology. Hygiene is a concern.", date: '5 weeks ago', sentiment: 'negative' },
  { author: 'Daniel M.', rating: 5, text: "Incredible latte art. These baristas are artists. The espresso is perfectly balanced every single time.", date: '5 weeks ago', sentiment: 'positive' },
  { author: 'Katie P.', rating: 2, text: "20 minute wait for drip coffee??? It's drip coffee. There should be a fast lane for simple orders.", date: '6 weeks ago', sentiment: 'negative' },
  { author: 'Ryan H.', rating: 4, text: "The croissants are fresh and flaky. Coffee is always good. A bit pricey but you get what you pay for.", date: '6 weeks ago', sentiment: 'positive' },
  { author: 'Lisa T.', rating: 3, text: "I've been coming here for a year and they still don't have mobile ordering. Every other café has it. Get with the times!", date: '6 weeks ago', sentiment: 'negative' },
  { author: 'Matt K.', rating: 5, text: "Hidden gem! The backyard patio is perfect for weekend brunch. Their avocado toast is next level.", date: '2 months ago', sentiment: 'positive' },
  { author: 'Olivia J.', rating: 2, text: "They never respond to reviews — not even the bad ones. Makes me think they don't care about improving.", date: '2 months ago', sentiment: 'negative' },
  { author: 'Steve W.', rating: 4, text: "Solid espresso, cool neighborhood. Wish they had more food options beyond pastries.", date: '2 months ago', sentiment: 'positive' },
  { author: 'Zoe A.', rating: 1, text: "The online menu hasn't been updated in forever. Half the items listed aren't available. Very misleading.", date: '2 months ago', sentiment: 'negative' },
  { author: 'Tyler B.', rating: 5, text: "My go-to spot. The staff is incredible, the coffee is perfect, and the playlist is always on point.", date: '2 months ago', sentiment: 'positive' },
  { author: 'Hannah G.', rating: 3, text: "Do they do events? I asked about booking for a birthday and nobody knew. Would be great if they had that info somewhere.", date: '3 months ago', sentiment: 'neutral' },
]

export const MOCK_ANALYSIS: BusinessAnalysis = {
  businessId: 'mock-coffee-1',
  businessType: 'coffee_shop',
  painPoints: [
    {
      issue: 'long_wait_times',
      label: 'Long Wait Times',
      frequency: 14,
      severity: 'high',
      exampleQuotes: [
        "I waited 25 minutes for a simple latte",
        "30 minute wait. The staff seemed overwhelmed",
        "20 minute wait for drip coffee???",
      ],
    },
    {
      issue: 'unresponsive_reviews',
      label: 'No Review Responses',
      frequency: 8,
      severity: 'high',
      exampleQuotes: [
        "I left a negative review a month ago and no one responded",
        "They never respond to reviews — not even the bad ones",
      ],
    },
    {
      issue: 'outdated_online_info',
      label: 'Outdated Menu & Hours Online',
      frequency: 10,
      severity: 'medium',
      exampleQuotes: [
        "The menu on Google is completely wrong",
        "The online menu hasn't been updated in forever",
        "Their Instagram says they close at 8pm but I showed up at 7:30 and they were closed",
      ],
    },
    {
      issue: 'no_mobile_ordering',
      label: 'No Mobile Ordering',
      frequency: 6,
      severity: 'medium',
      exampleQuotes: [
        "Wish they had a mobile ordering option so I could skip the line",
        "Every other café has mobile ordering. Get with the times!",
      ],
    },
    {
      issue: 'phone_unanswered',
      label: 'Phone Goes Unanswered',
      frequency: 4,
      severity: 'medium',
      exampleQuotes: [
        "Tried calling ahead and no one picked up. Called 4 times.",
        "Do they not answer the phone?",
      ],
    },
  ],
  strengths: [
    { label: 'Coffee Quality', mentions: 18 },
    { label: 'Ambiance & Vibe', mentions: 12 },
    { label: 'Friendly Staff', mentions: 8 },
    { label: 'Pastries & Food', mentions: 6 },
  ],
  unansweredQuestions: [
    'Is there parking nearby?',
    'Do you have reliable WiFi?',
    'Can I book for events/parties?',
    'Do you do catering?',
    'What are the actual current hours?',
  ],
  workflows: MOCK_WORKFLOWS(),
  analyzedAt: new Date().toISOString(),
}

function MOCK_WORKFLOWS(): Workflow[] {
  return [
    {
      id: 'wf-review-responder',
      name: 'Smart Review Responder',
      description: 'Automatically monitors and drafts personalized responses to Google reviews. Uses browser to check for new reviews, analyzes sentiment, and generates empathetic responses that address specific complaints.',
      trigger: 'Every 4 hours during business hours',
      toolsUsed: ['browser', 'tts'],
      userFacing: true,
      actions: [
        'Browse Google Maps listing → check for new reviews',
        'Analyze review sentiment and extract key complaints',
        'Generate personalized response acknowledging specific issues',
        'Draft response for owner approval or auto-post',
        'If severe complaint → alert owner via SMS with voice summary',
      ],
      evalMetrics: [
        { name: 'response_posted', description: 'Was a response posted?', type: 'boolean' },
        { name: 'response_time_hrs', description: 'Hours between review and response', type: 'number', target: 4 },
        { name: 'sentiment_match', description: 'Response tone matches review severity', type: 'percentage', target: 90 },
        { name: 'customer_updated', description: 'Did customer update/improve their review?', type: 'boolean' },
      ],
      painPointId: 'unresponsive_reviews',
      status: 'suggested',
      feedback: null,
      confidence: 0.94,
    },
    {
      id: 'wf-phone-agent',
      name: 'AI Phone Receptionist',
      description: 'Voice AI agent that answers phone calls, handles common questions (hours, parking, menu), takes catering inquiries, and transfers to staff for complex requests.',
      trigger: 'Inbound phone call',
      toolsUsed: ['voice', 'tts', 'calendar'],
      userFacing: true,
      actions: [
        'Answer inbound call with friendly greeting',
        'Identify caller intent (hours, menu, catering, reservation)',
        'Answer from knowledge base built from website + menu',
        'For catering → collect details + schedule callback',
        'For complaints → empathize, log, alert manager',
      ],
      evalMetrics: [
        { name: 'call_answered', description: 'Was the call picked up?', type: 'boolean' },
        { name: 'intent_accuracy', description: 'Correctly identified caller intent', type: 'percentage', target: 85 },
        { name: 'resolution_rate', description: 'Caller question resolved without transfer', type: 'percentage', target: 70 },
        { name: 'caller_satisfaction', description: 'Post-call rating', type: 'number', target: 4 },
      ],
      painPointId: 'phone_unanswered',
      status: 'suggested',
      feedback: null,
      confidence: 0.91,
    },
    {
      id: 'wf-listing-sync',
      name: 'Listing & Menu Sync Checker',
      description: 'Browses all online listings (Google, Yelp, website, Instagram) and compares menu items, hours, and pricing. Flags discrepancies and auto-generates update suggestions.',
      trigger: 'Weekly on Monday 9 AM',
      toolsUsed: ['browser', 'image_model'],
      userFacing: false,
      actions: [
        'Browse Google Maps listing → extract menu & hours',
        'Browse Yelp listing → extract menu & hours',
        'Browse business website → extract menu & hours',
        'Use vision AI to read menu images/PDFs',
        'Compare all sources → flag discrepancies',
        'Generate report with specific fixes needed',
      ],
      evalMetrics: [
        { name: 'platforms_checked', description: 'Number of platforms scanned', type: 'number', target: 4 },
        { name: 'discrepancies_found', description: 'Mismatches detected', type: 'number' },
        { name: 'issues_fixed', description: 'Were flagged issues resolved?', type: 'boolean' },
        { name: 'accuracy', description: 'Accuracy of discrepancy detection', type: 'percentage', target: 95 },
      ],
      painPointId: 'outdated_online_info',
      status: 'suggested',
      feedback: null,
      confidence: 0.88,
    },
    {
      id: 'wf-queue-monitor',
      name: 'Wait Time & Queue Monitor',
      description: 'Monitors real-time customer flow patterns and review mentions of wait times. Alerts staff during predicted rush periods and suggests staffing adjustments.',
      trigger: 'Every 30 min during business hours',
      toolsUsed: ['browser', 'sms', 'video'],
      userFacing: false,
      actions: [
        'Analyze recent reviews for wait time mentions',
        'Cross-reference with Google Popular Times data',
        'Predict upcoming rush based on day/time patterns',
        'Alert staff 30 min before predicted rush',
        'Suggest adding extra barista during peak windows',
        'Track if wait complaint frequency decreases over time',
      ],
      evalMetrics: [
        { name: 'rush_predicted', description: 'Rush period correctly predicted', type: 'boolean' },
        { name: 'alert_sent', description: 'Staff alerted before rush', type: 'boolean' },
        { name: 'complaint_reduction', description: 'Reduction in wait-related complaints', type: 'percentage', target: 30 },
        { name: 'accuracy', description: 'Prediction accuracy vs actual', type: 'percentage', target: 75 },
      ],
      painPointId: 'long_wait_times',
      status: 'suggested',
      feedback: null,
      confidence: 0.82,
    },
    {
      id: 'wf-qa-responder',
      name: 'Auto Q&A Responder',
      description: 'Monitors Google Q&A section and unanswered questions in reviews. Automatically drafts accurate answers based on business knowledge base.',
      trigger: 'Daily at 10 AM',
      toolsUsed: ['browser', 'tts'],
      userFacing: true,
      actions: [
        'Browse Google Maps Q&A section for unanswered questions',
        'Scan recent reviews for questions posed by customers',
        'Match questions to knowledge base (hours, parking, WiFi, etc.)',
        'Draft clear, helpful answers',
        'Post answers or queue for owner approval',
      ],
      evalMetrics: [
        { name: 'questions_answered', description: 'Number of questions responded to', type: 'number' },
        { name: 'answer_accuracy', description: 'Answer matches verified info', type: 'percentage', target: 95 },
        { name: 'response_time', description: 'Hours from question to answer', type: 'number', target: 24 },
      ],
      painPointId: 'no_mobile_ordering',
      status: 'suggested',
      feedback: null,
      confidence: 0.86,
    },
  ]
}
