import { BusinessInfo, Review, PainPoint, Workflow, BusinessAnalysis, EvalMetric } from './types';

const businessId = 'biz_mock_brewhaus_001';

const mockReviews: Review[] = [
  { author: 'Sarah M.', rating: 5, date: '2025-01-15', text: 'Absolutely love this place! The lavender latte is to die for. Cozy atmosphere and the baristas are always so friendly. My go-to spot for remote work.', sentiment: 'positive', helpful_count: 12 },
  { author: 'James T.', rating: 1, date: '2025-01-14', text: 'Waited 25 minutes for a simple black coffee. The line was out the door and they only had one person working the register. Ridiculous for a Saturday morning.', sentiment: 'negative', helpful_count: 8 },
  { author: 'Priya K.', rating: 4, date: '2025-01-13', text: 'Great coffee quality but the WiFi keeps dropping. Hard to get any real work done here. Would be perfect otherwise.', sentiment: 'neutral', helpful_count: 15 },
  { author: 'Mike R.', rating: 2, date: '2025-01-12', text: 'The pastries are stale most of the time. I\'ve tried three different times and each time the croissants were clearly from the day before. Coffee is good though.', sentiment: 'negative', helpful_count: 6 },
  { author: 'Emily C.', rating: 5, date: '2025-01-11', text: 'Best oat milk latte in the city! The seasonal menu is always creative and delicious. Staff remembers my name which is such a nice touch.', sentiment: 'positive', helpful_count: 9 },
  { author: 'David L.', rating: 3, date: '2025-01-10', text: 'Decent coffee, nothing special. The prices have gone up a lot recently — $7 for a latte is steep. At least the portions are generous.', sentiment: 'neutral', helpful_count: 4 },
  { author: 'Ana S.', rating: 1, date: '2025-01-09', text: 'Terrible experience. They got my order wrong twice, charged me for the wrong drink, and the manager was dismissive about it. Won\'t be coming back.', sentiment: 'negative', helpful_count: 11 },
  { author: 'Tom W.', rating: 5, date: '2025-01-08', text: 'This is my office away from the office. Great ambiance, outlets at every table, and the cold brew is phenomenal. The pour-over is worth the wait.', sentiment: 'positive', helpful_count: 7 },
  { author: 'Rachel G.', rating: 4, date: '2025-01-07', text: 'Love the aesthetic and the coffee is consistently good. Only complaint is there\'s never enough seating during peak hours. Need more tables!', sentiment: 'positive', helpful_count: 5 },
  { author: 'Kevin H.', rating: 2, date: '2025-01-06', text: 'The mobile ordering is broken half the time. I placed an order online, showed up, and they had no record of it. Wasted 30 minutes of my lunch break.', sentiment: 'negative', helpful_count: 13 },
  { author: 'Lisa P.', rating: 5, date: '2025-01-05', text: 'Brought my book club here and everyone was impressed. The space is beautiful, the drinks are artful, and they were so accommodating with our large group.', sentiment: 'positive', helpful_count: 3 },
  { author: 'Chris D.', rating: 3, date: '2025-01-04', text: 'Hit or miss depending on who\'s working. Some days the coffee is amazing, other days it tastes burnt. Consistency could be better.', sentiment: 'neutral', helpful_count: 6 },
  { author: 'Maria F.', rating: 1, date: '2025-01-03', text: 'Found a hair in my cappuccino. When I brought it to their attention, they offered to remake it but didn\'t apologize or comp the drink. Basic hygiene please.', sentiment: 'negative', helpful_count: 18 },
  { author: 'Josh B.', rating: 5, date: '2025-01-02', text: 'The single origin Ethiopian is incredible. These guys clearly care about sourcing quality beans. Also love that they have a loyalty program now.', sentiment: 'positive', helpful_count: 4 },
  { author: 'Nina V.', rating: 4, date: '2025-01-01', text: 'Charming little spot! The matcha is legit ceremonial grade. Only thing is parking is a nightmare. They need to validate or something.', sentiment: 'positive', helpful_count: 7 },
  { author: 'Alex T.', rating: 2, date: '2024-12-31', text: 'Way too loud. They started playing live music on weekends and it makes it impossible to have a conversation. Used to be a chill spot, now it\'s a bar.', sentiment: 'negative', helpful_count: 9 },
  { author: 'Sophie L.', rating: 5, date: '2024-12-30', text: 'My happy place 💛 The baristas here are genuine coffee nerds and it shows. They talked me through their whole brewing process. Amazing experience.', sentiment: 'positive', helpful_count: 5 },
  { author: 'Ryan M.', rating: 3, date: '2024-12-29', text: 'Good coffee but their hours are weird. They close at 3pm on weekdays? Who closes a coffee shop at 3pm? Would come more if they were open later.', sentiment: 'neutral', helpful_count: 14 },
  { author: 'Olivia N.', rating: 1, date: '2024-12-28', text: 'They changed their recipe for the vanilla latte and it\'s terrible now. It used to be my favorite drink anywhere. Now it tastes like artificial syrup. So disappointed.', sentiment: 'negative', helpful_count: 10 },
  { author: 'Daniel K.', rating: 5, date: '2024-12-27', text: 'Best coffee shop in Portland, hands down. The atmosphere, the quality, the people — everything is top-tier. Worth driving across town for.', sentiment: 'positive', helpful_count: 8 },
  { author: 'Zoe W.', rating: 4, date: '2024-12-26', text: 'Really solid spot. The breakfast sandwich is surprisingly good too. They use local bread and the egg is always perfectly done. Coffee is great as always.', sentiment: 'positive', helpful_count: 3 },
  { author: 'Marcus J.', rating: 2, date: '2024-12-25', text: 'I asked for dairy-free and they used regular milk. When I mentioned my allergy they didn\'t seem concerned at all. Could have been a serious issue.', sentiment: 'negative', helpful_count: 16 },
  { author: 'Jen H.', rating: 5, date: '2024-12-24', text: 'The holiday specials are AMAZING. The gingerbread latte is actually made with real gingerbread syrup, not that artificial stuff. Can taste the difference.', sentiment: 'positive', helpful_count: 6 },
  { author: 'Peter A.', rating: 3, date: '2024-12-23', text: 'Bathroom is always out of soap or paper towels. For a place that charges $6+ per drink, basic maintenance shouldn\'t be an issue. Coffee itself is fine.', sentiment: 'neutral', helpful_count: 7 },
  { author: 'Mia C.', rating: 5, date: '2024-12-22', text: 'I come here every morning before work and it genuinely makes my day better. The regulars are friendly, the staff knows my order, it feels like community.', sentiment: 'positive', helpful_count: 11 },
  { author: 'Ben S.', rating: 1, date: '2024-12-21', text: 'Overpriced and overhyped. $7.50 for a medium latte that tastes the same as any chain. The "artisanal" branding is just marketing. Save your money.', sentiment: 'negative', helpful_count: 5 },
  { author: 'Grace L.', rating: 4, date: '2024-12-20', text: 'Love this place but wish they had more food options. The pastry case is small and they run out by noon. A proper lunch menu would make this perfect.', sentiment: 'positive', helpful_count: 8 },
  { author: 'Tyler R.', rating: 2, date: '2024-12-19', text: 'The app is terrible. Crashes constantly, can\'t save favorites, and the rewards never seem to track correctly. Just use Square or something that works.', sentiment: 'negative', helpful_count: 12 },
  { author: 'Amanda Q.', rating: 5, date: '2024-12-18', text: 'Hosted a small event here and the team went above and beyond. They set up a special tasting station and the owner personally curated the menu. Incredible service.', sentiment: 'positive', helpful_count: 4 },
  { author: 'Steve F.', rating: 3, date: '2024-12-17', text: 'It\'s fine. Nothing wrong with it but nothing that blows me away either. I think people overhype it because of the Instagram aesthetic. The cortado is decent.', sentiment: 'neutral', helpful_count: 3 },
  { author: 'Lauren E.', rating: 5, date: '2024-12-16', text: 'The cold brew here has ruined me for all other cold brews. It\'s so smooth and never bitter. I buy the take-home bottles now too. Obsessed.', sentiment: 'positive', helpful_count: 9 },
  { author: 'Jake P.', rating: 1, date: '2024-12-15', text: 'Ants everywhere. I watched three ants crawl across my table while I was drinking. Told the staff and they shrugged. Reported to health department.', sentiment: 'negative', helpful_count: 22 },
  { author: 'Samantha Y.', rating: 4, date: '2024-12-14', text: 'Great spot for studying. Quiet enough during weekdays, good music, and the chai latte is the best I\'ve had. Only wish they had more power outlets upstairs.', sentiment: 'positive', helpful_count: 6 },
  { author: 'Eric O.', rating: 2, date: '2024-12-13', text: 'The new staff clearly hasn\'t been trained properly. My pour-over was under-extracted and they didn\'t know what I meant when I mentioned it. Miss the old crew.', sentiment: 'negative', helpful_count: 7 },
  { author: 'Diana M.', rating: 5, date: '2024-12-12', text: 'This place is a gem. Discovered it last month and now I\'m here 4x a week. The owners clearly pour their hearts into every detail. Supporting local never felt so good.', sentiment: 'positive', helpful_count: 10 },
  { author: 'Paul I.', rating: 3, date: '2024-12-11', text: 'Good coffee but they need a better queuing system. It\'s confusing where to stand, where to pick up, and the counter is always chaotic during rush hour.', sentiment: 'neutral', helpful_count: 5 },
  { author: 'Heather N.', rating: 4, date: '2024-12-10', text: 'Really appreciate that they source ethically and display the origin info for each bean. Wish more places did this. The espresso is punchy and complex.', sentiment: 'positive', helpful_count: 4 },
  { author: 'Ian B.', rating: 1, date: '2024-12-09', text: 'Rude staff. Asked a simple question about allergens and the barista rolled their eyes. Customer service matters, especially at these prices.', sentiment: 'negative', helpful_count: 14 },
  { author: 'Chloe T.', rating: 5, date: '2024-12-08', text: 'Brought my out-of-town friends here and they couldn\'t stop raving about it. The aesthetic is perfect, the drinks are beautiful AND delicious. Portland\'s best kept secret.', sentiment: 'positive', helpful_count: 7 },
  { author: 'Nathan Z.', rating: 4, date: '2024-12-07', text: 'Solid coffee shop. My only gripe is no drive-through or curbside pickup option. Sometimes I just want to grab and go without finding parking and going inside.', sentiment: 'positive', helpful_count: 3 },
];

export const mockBusiness: BusinessInfo = {
  id: businessId,
  name: 'BrewHaus Coffee Roasters',
  type: 'Coffee Shop',
  rating: 4.2,
  review_count: 847,
  address: '2847 NW Thurman St, Portland, OR 97210',
  phone: '(503) 555-0142',
  website: 'https://brewhauspdx.com',
  hours: [
    'Mon-Fri: 6:30 AM - 3:00 PM',
    'Sat-Sun: 7:00 AM - 5:00 PM',
  ],
  price_level: '$$',
  photos: [
    '/mock/brewhaus-exterior.jpg',
    '/mock/brewhaus-interior.jpg',
    '/mock/brewhaus-latte.jpg',
  ],
  reviews: mockReviews,
  scraped_services: [
    'Espresso drinks',
    'Pour-over bar',
    'Cold brew on tap',
    'Pastries & breakfast sandwiches',
    'Coffee bean retail',
    'Event hosting',
    'Catering',
    'Loyalty rewards program',
  ],
  scraped_menu: [
    'Lavender Latte - $6.50',
    'Oat Milk Latte - $6.00',
    'Single Origin Pour Over - $5.50',
    'Cold Brew (16oz) - $5.00',
    'Cappuccino - $5.50',
    'Matcha Latte - $6.50',
    'Chai Latte - $5.50',
    'Cortado - $4.50',
    'Gingerbread Latte (seasonal) - $7.00',
    'Breakfast Sandwich - $8.50',
    'Croissant - $4.00',
    'Muffin of the Day - $3.50',
  ],
  scraped_pricing: [
    { item: 'Espresso', price: '$3.50' },
    { item: 'Latte', price: '$5.50-$7.00' },
    { item: 'Pour Over', price: '$5.50' },
    { item: 'Cold Brew', price: '$5.00' },
    { item: 'Pastries', price: '$3.50-$4.50' },
    { item: 'Breakfast Sandwich', price: '$8.50' },
    { item: 'Retail Beans (12oz)', price: '$18.00' },
  ],
  screenshots: [],
  discovered_at: new Date().toISOString(),
  maps_url: 'https://maps.google.com/maps?q=brewhaus+coffee+roasters+portland',
};

export const mockPainPoints: PainPoint[] = [
  {
    issue: 'Long Wait Times',
    frequency: 12,
    severity: 'high',
    example_quotes: [
      'Waited 25 minutes for a simple black coffee',
      'Wasted 30 minutes of my lunch break',
      'The counter is always chaotic during rush hour',
    ],
    category: 'operations',
  },
  {
    issue: 'Inconsistent Quality',
    frequency: 8,
    severity: 'medium',
    example_quotes: [
      'Some days the coffee is amazing, other days it tastes burnt',
      'They changed their recipe for the vanilla latte and it\'s terrible now',
      'My pour-over was under-extracted',
    ],
    category: 'product',
  },
  {
    issue: 'Technology Issues',
    frequency: 7,
    severity: 'high',
    example_quotes: [
      'The mobile ordering is broken half the time',
      'The app is terrible. Crashes constantly',
      'WiFi keeps dropping',
    ],
    category: 'technology',
  },
  {
    issue: 'Staff Training & Service',
    frequency: 6,
    severity: 'medium',
    example_quotes: [
      'The new staff clearly hasn\'t been trained properly',
      'The manager was dismissive about it',
      'I asked for dairy-free and they used regular milk',
    ],
    category: 'service',
  },
  {
    issue: 'Cleanliness & Maintenance',
    frequency: 4,
    severity: 'critical',
    example_quotes: [
      'Found a hair in my cappuccino',
      'Ants everywhere',
      'Bathroom is always out of soap or paper towels',
    ],
    category: 'hygiene',
  },
];

export const mockWorkflows: Workflow[] = [
  {
    id: 'wf_review_monitor',
    business_id: businessId,
    name: 'Review Sentiment Monitor',
    description: 'Continuously monitors Google Maps and Yelp reviews, detects negative sentiment spikes, and alerts the owner with a summary + suggested response drafts.',
    trigger: 'cron: every 2 hours during business hours',
    tools_used: ['browser', 'llm'],
    user_facing: false,
    actions: [
      'Open Google Maps listing via Browserbase',
      'Scrape latest reviews since last check',
      'Analyze sentiment using Claude',
      'If negative spike detected, generate alert',
      'Draft personalized response for each negative review',
      'Send summary to owner via SMS/WhatsApp',
    ],
    eval_metrics: [
      { name: 'reviews_scraped', description: 'Number of reviews successfully scraped per run', measurement: 'count_per_run' },
      { name: 'sentiment_accuracy', description: 'Accuracy of sentiment classification', target: '>95%', measurement: 'manual_review_sample' },
      { name: 'alert_latency', description: 'Time from review posted to owner alerted', target: '<2 hours', measurement: 'timestamp_diff' },
      { name: 'response_quality', description: 'Owner satisfaction with draft responses', measurement: 'thumbs_up_rate' },
    ],
    status: 'suggested',
    feedback: { thumbs_up: 0, thumbs_down: 0, edits: [] },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'wf_phone_assistant',
    business_id: businessId,
    name: 'AI Phone Receptionist',
    description: 'Answers phone calls during busy hours or after close. Handles common questions (hours, menu, reservations), takes messages, and escalates urgent issues.',
    trigger: 'event: incoming_phone_call',
    tools_used: ['tts', 'voice', 'llm'],
    user_facing: true,
    actions: [
      'Answer incoming call via Daily/Pipecat',
      'Greet caller with business name',
      'Use speech-to-text to understand request',
      'Query business knowledge base for answer',
      'Respond with TTS in natural voice',
      'If unable to help, offer to take a message',
      'Log call summary and any follow-ups needed',
    ],
    eval_metrics: [
      { name: 'calls_handled', description: 'Total calls handled without human intervention', measurement: 'count_per_day' },
      { name: 'resolution_rate', description: 'Percentage of calls resolved without escalation', target: '>80%', measurement: 'resolved_vs_escalated' },
      { name: 'caller_satisfaction', description: 'Post-call satisfaction rating', target: '>4/5', measurement: 'survey_score' },
      { name: 'avg_call_duration', description: 'Average call length', target: '<2 min', measurement: 'time_seconds' },
    ],
    status: 'suggested',
    feedback: { thumbs_up: 0, thumbs_down: 0, edits: [] },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'wf_quality_inspector',
    business_id: businessId,
    name: 'Visual Quality Inspector',
    description: 'Uses camera feeds to monitor food presentation, cleanliness standards, and customer density. Sends alerts when standards slip or when rush hour is detected.',
    trigger: 'cron: every 15min during business hours',
    tools_used: ['image_model', 'camera', 'llm'],
    user_facing: false,
    actions: [
      'Capture frames from counter/display camera',
      'Analyze food presentation quality using vision model',
      'Check pastry case freshness (visual age indicators)',
      'Monitor cleanliness of visible surfaces',
      'Estimate customer count and queue length',
      'Generate report with flagged issues',
      'Alert manager if cleanliness score drops below threshold',
    ],
    eval_metrics: [
      { name: 'inspections_completed', description: 'Successful inspection runs per day', measurement: 'count_per_day' },
      { name: 'issue_detection_accuracy', description: 'Accuracy of flagged cleanliness/quality issues', target: '>90%', measurement: 'manual_verification' },
      { name: 'false_positive_rate', description: 'Rate of incorrectly flagged issues', target: '<10%', measurement: 'false_positives_per_total' },
      { name: 'queue_estimation_accuracy', description: 'Accuracy of customer count estimation', target: '±2 people', measurement: 'manual_count_comparison' },
    ],
    status: 'suggested',
    feedback: { thumbs_up: 0, thumbs_down: 0, edits: [] },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'wf_social_manager',
    business_id: businessId,
    name: 'Social Media & Engagement Manager',
    description: 'Monitors social media mentions, generates content ideas based on trending topics, drafts posts, and tracks competitor activity.',
    trigger: 'cron: every 4 hours + event: mention_detected',
    tools_used: ['browser', 'llm', 'image_model'],
    user_facing: false,
    actions: [
      'Scan Instagram, Twitter, TikTok for brand mentions',
      'Analyze competitor social media activity',
      'Identify trending coffee/food topics',
      'Generate 3 post ideas with suggested images',
      'Draft Instagram captions and hashtag sets',
      'Track engagement metrics on recent posts',
      'Send weekly social media performance report',
    ],
    eval_metrics: [
      { name: 'mentions_tracked', description: 'Social mentions captured across platforms', measurement: 'count_per_week' },
      { name: 'content_ideas_generated', description: 'Unique content ideas produced', measurement: 'count_per_week' },
      { name: 'draft_approval_rate', description: 'Percentage of drafts approved by owner', target: '>70%', measurement: 'approved_vs_total' },
      { name: 'engagement_lift', description: 'Week-over-week engagement improvement', target: '>5%', measurement: 'engagement_rate_delta' },
    ],
    status: 'suggested',
    feedback: { thumbs_up: 0, thumbs_down: 0, edits: [] },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockAnalysis: BusinessAnalysis = {
  business_id: businessId,
  business_type: 'coffee_shop',
  pain_points: mockPainPoints,
  strengths: [
    'Exceptional coffee quality and sourcing',
    'Strong community atmosphere and loyal regulars',
    'Beautiful aesthetic and Instagram-worthy presentation',
    'Knowledgeable and passionate baristas',
    'Creative seasonal menu offerings',
    'Ethical sourcing with transparent origin info',
  ],
  unanswered_questions: [
    'Do you offer drive-through or curbside pickup?',
    'Are you planning to extend weekday hours?',
    'Is there a group or event booking system?',
    'Do you accommodate dietary restrictions beyond dairy-free?',
    'Will the mobile app be fixed/updated?',
  ],
  suggested_workflows: mockWorkflows,
  analyzed_at: new Date().toISOString(),
};
